**Creating Numpy arrays**

In [3]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr4=np.ones((3,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
arr6=np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [11]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [12]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

**Numpy array properties and Attributes**

In [13]:
arr1.shape

(5,)

In [14]:
arr2.shape

(2, 3)

In [15]:
arr4.shape

(3, 4)

In [16]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
arr9.shape

(2, 2, 2)

In [18]:
arr9.ndim

3

In [19]:
arr2.ndim

2

In [20]:
arr1.ndim

1

In [21]:
arr1.size

5

In [22]:
arr9.size

8

In [23]:
arr9.itemsize

8

In [24]:
arr8.itemsize

8

In [25]:
arr8.dtype

dtype('float64')

In [26]:
arr2.dtype

dtype('int64')

In [27]:
arr9.dtype

dtype('int64')

In [28]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [29]:
lista=range(100)
arr11=np.arange(100)

In [30]:
import sys

In [31]:
print(sys.getsizeof(89)*len(lista))

2800


In [32]:
print(arr11.itemsize*arr11.size)

800


In [33]:
import time

**Numpy array vs Python list**

In [34]:
x=range(10000000)
y=range(10000000,20000000)
start_time=time.time()

c=[(x,y)for x,y in zip(x,y)]
print(time.time()-start_time)

2.8500614166259766


In [35]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start_time=time.time()
c=a+b
print(time.time()-start_time)

0.6107802391052246


**Indexing,Slicing and Iteration**

In [36]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [38]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [39]:
arr12[4:2,1:3]

array([], shape=(0, 2), dtype=int64)

In [40]:
arr12[4:6,2:5]

array([[18, 19],
       [22, 23]])

In [41]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [43]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


**Numpy array Operations**

In [44]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [45]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [46]:
arr1+arr2

array([ 5,  7,  9, 11, 13, 15])

In [47]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [48]:
arr1%arr2

array([1, 2, 3, 4, 5, 6])

In [49]:
arr1/arr2

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
       0.66666667])

In [50]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [51]:
arr1+2

array([3, 4, 5, 6, 7, 8])

In [52]:
(arr1-arr2)*2

array([-6, -6, -6, -6, -6, -6])

In [53]:
arr1>3

array([False, False, False,  True,  True,  True])

In [54]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [55]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [56]:
arr1.dot(arr3)

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

In [ ]:
arr4

In [ ]:
arr4.max()

In [ ]:
arr4.min()

In [ ]:
arr4.min(axis=0)

In [ ]:
arr4.max(axis=0)

In [ ]:
arr4.min(axis=1)

In [ ]:
arr4.max(axis=1)

In [ ]:
arr4.sum()

In [ ]:
arr4.sum(axis=0)

In [ ]:
arr4.mean()

In [ ]:
arr4.median()

In [ ]:
arr4.std()

In [ ]:
np.sin(arr4)

In [ ]:
np.median(arr4)

**Reshaping Numpy Array**

In [ ]:
arr4.ndim

In [ ]:
arr4.ravel()

In [ ]:
arr4.transpose()

In [ ]:
 arr5=np.arange(12,18).reshape(2,3)

In [ ]:
np.hstack((arr3,arr5))

In [ ]:
np.vstack((arr3,arr5))

In [ ]:
np.hsplit(arr3,3)  

In [ ]:
np.vsplit(arr3,2) 

**Fancy Indexing**

In [ ]:
arr8=np.arange(24).reshape(6,4)

In [ ]:
arr8

In [ ]:
arr8[[0,2,4]]

In [ ]:
arr8[[1,3]]

**Indexing with Boolean Array**

In [ ]:
arr=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr

In [ ]:
arr[0][2]

In [ ]:
arr>50

In [ ]:
(arr>50).shape

In [ ]:
arr[arr>50]

In [ ]:
arr[(arr>50)&(arr%2!=0)]

In [ ]:
arr[(arr>50)&(arr%2!=0)]=0

In [ ]:
arr

**Plotting graphs**

In [ ]:
x=np.linspace(-40,40,100)

In [ ]:
x

In [ ]:
x.size

In [ ]:
y=np.sin(x)

In [ ]:
y.size

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.plot(x,y)

In [ ]:
y=x*x+2*x+6

In [ ]:
plt.plot(x,y)

**Broadcasting**

In [ ]:
a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

In [ ]:
a1+a2

In [ ]:
a3=np.arange(9).reshape(3,3)
a4=np.arange(3).reshape(1,3)
print(a3,a4)

In [ ]:
a3+a4

**Rules of Broadcasting**

In [60]:
# if x=m and y=n operation with take place
a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [59]:
# if x=1 and y=n then also operation will take place(same Dimension)
a5=np.arange(3).reshape(1,3)
a6=np.arange(12).reshape(4,3)
print(a5,a6)

[[0 1 2]] [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [58]:
a5+a6

NameError: name 'a5' is not defined

In [ ]:
# if x=1 and y!=n then also operation will not take place 
a9= np.arange(3).reshape(1,3)
a10= np.arange(16).reshape(4,4)

print(a9)
print(a10)

In [ ]:
a9+a10

In [ ]:
# if x=1 and n=1 then y==m,operation take place
a11=np.arange(3).reshape(1,3)
a12=np.arange(3).reshape(3,1)

print(a11)
print(a12)

In [ ]:
a11+a12

In [ ]:
# if x=1 and y=1 then the operation will take place no matter what
a13=np.arange(1).reshape(1,1)
a14=np.arange(20).reshape(4,5)

print(a13)
print(a14)

In [ ]:
a13+14

In [ ]:
# if they are of different dimension
a15=np.arange(4)
a16=np.arange(20).reshape(5,4)

print(a15)
print(a16)

In [ ]:
a15+a16

In [67]:
np.random.random()

0.7203244934421581

In [66]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [74]:
np.random.uniform(1,100)


54.34285666633234

In [75]:
np.random.uniform(1,100,10)

array([42.50025693, 68.83673054, 21.24077272, 87.9336262 ,  3.71137173,
       67.37628351, 42.31317543, 56.31029302, 14.89830692, 20.61204742])

In [86]:
np.random.randint(1,10)

2

In [87]:
np.random.randint(1,10,5)

array([4, 5, 9, 2, 5])

In [91]:
np.random.randint(1,10,15).reshape(3,5)

array([[1, 9, 8, 8, 2],
       [2, 4, 1, 9, 7],
       [5, 6, 7, 3, 6]])

In [100]:
a=np.random.randint(1,10,6)
a

array([5, 1, 3, 1, 8, 2])

In [101]:
np.max(a)

8

In [102]:
np.min(a)

1

In [103]:
np.argmax(a)

4

In [104]:
a[np.argmax(a)]

8

In [105]:
a[np.argmin(a)]

1

In [107]:
np.argmin(a)

1

In [121]:
a=np.random.randint(1,100,6)
a

array([43, 21, 49, 23, 14, 98])

In [120]:
a[a%2==1]=-1
a

array([72, -1, -1, 16,  6, 18])

In [122]:
np.where(a%2==1,-1,a)

array([-1, -1, -1, -1, 14, 98])

In [123]:
a

array([43, 21, 49, 23, 14, 98])

In [124]:
out=np.where(a%2==1,-1,a)
out

array([-1, -1, -1, -1, 14, 98])

In [125]:
a=np.random.randint(1,50,10)
a

array([21, 11, 33, 26, 22, 40, 33, 20, 26, 15])

In [128]:
a=np.sort(a)
a

array([11, 15, 20, 21, 22, 26, 26, 33, 33, 40])

In [130]:
np.percentile(a,25)

20.25

In [132]:
np.percentile(a,50)

24.0

In [134]:
np.percentile(a,99.8)

39.873999999999995