In [24]:
import numpy as np 
n=np.array([10,20,30,40])
n

array([10, 20, 30, 40])

In [25]:
n=np.array([[10,20,30,40],[40,30,20,10]])
n

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [26]:
type(n)

numpy.ndarray

In [8]:
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [6]:
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
n1=np.zeros((2,2))
n1

array([[0., 0.],
       [0., 0.]])

In [10]:
n2=np.full((2,2),10)
n2

array([[10, 10],
       [10, 10]])

In [14]:
n2=np.full((4,5),10)
n2

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [17]:
n3=np.arange(10,20)
n3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
n3=np.arange(10,70,5)
n3

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

In [19]:
n3=np.arange(10,200,5)
n3

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
       140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195])

In [20]:
n4=np.random.randint(1,100,5)
n4

array([61,  3, 84, 53, 75])

In [21]:
n5=np.random.randint(1,100,5)
n5

array([64, 15, 10, 86, 64])

In [22]:
n5=np.random.randint(1,100,10)
n5

array([29, 64, 69, 32, 79, 47, 86, 79, 85,  2])

In [23]:
n5=np.random.randint(1,100,20)
n5

array([17, 87, 98, 21, 56, 26, 58, 70, 22, 71, 27, 87, 74, 45, 76, 37, 71,
       23, 28, 43])

In [38]:
n6=np.array([[10,20,30],[1,2,3]])
n6

array([[10, 20, 30],
       [ 1,  2,  3]])

In [39]:
n6=np.array([[10,20,30],[1,2,3]])
n6.shape

(2, 3)

In [40]:
n6.shape = (3,2)
n6

array([[10, 20],
       [30,  1],
       [ 2,  3]])

In [41]:
n7=np.array([10,20,30])
n8=np.array([11,22,33])
np.vstack((n7,n8))

array([[10, 20, 30],
       [11, 22, 33]])

In [42]:
np.hstack((n7,n8))

array([10, 20, 30, 11, 22, 33])

In [43]:
np.column_stack((n7,n8))

array([[10, 11],
       [20, 22],
       [30, 33]])

In [45]:
n9=np.array([10,20,30,11,22])
n10=np.array([11,22,33])

In [48]:
np.intersect1d(n9,n10)

array([11, 22])

In [49]:
np.setdiff1d(n9,n10)

array([10, 20, 30])

In [50]:
np.setdiff1d(n10,n9)

array([33])

In [52]:
n11=np.array([10,20])
n12=np.array([11,22])
np.sum([n11,n12])

63

In [53]:
np.sum([n11,n12],axis=0)

array([21, 42])

In [54]:
np.sum([n11,n12],axis=1)

array([30, 33])

In [56]:
n11=np.array([10,20,30])
n11=n11+1
n11

array([11, 21, 31])

In [57]:
n11=n11-1
n11

array([10, 20, 30])

In [58]:
n11=n11*3
n11

array([30, 60, 90])

In [59]:
n11=n11/2
n11

array([15., 30., 45.])

In [60]:
n11=n11%2
n11

array([1., 0., 1.])

In [62]:
n13=np.array([20,90,30,40,50,60])
np.mean(n13)

48.333333333333336

In [63]:
np.std(n13)

22.66911751455907

In [64]:
np.median(n13)

45.0

In [67]:
n14=np.array([[20,90,30],[40,50,60],[11,22,33]])
n14

array([[20, 90, 30],
       [40, 50, 60],
       [11, 22, 33]])

In [68]:
n14[0]

array([20, 90, 30])

In [69]:
n14[1]

array([40, 50, 60])

In [70]:
n14[:,1]

array([90, 50, 22])

In [71]:
n14[:,2]

array([30, 60, 33])

In [72]:
n14[2:,2]

array([33])

In [75]:
n14[1:2,2]

array([60])

In [76]:
n14

array([[20, 90, 30],
       [40, 50, 60],
       [11, 22, 33]])

In [77]:
n14.transpose()

array([[20, 40, 11],
       [90, 50, 22],
       [30, 60, 33]])

In [78]:
n15=np.array([[1,2,3],[4,5,6],[7,8,9]])
n15

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
n14.dot(n15)

array([[590, 730, 870],
       [660, 810, 960],
       [330, 396, 462]])

In [81]:
n15.dot(n14)

array([[ 133,  256,  249],
       [ 346,  742,  618],
       [ 559, 1228,  987]])

In [82]:
n16=np.array([1,2,3,4,5,6,7,8,9])
np.save('my_numpy',n16)

In [83]:
n17=np.load('my_numpy.npy')
n17

array([1, 2, 3, 4, 5, 6, 7, 8, 9])